apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.label.name }}
spec:
  ports:
  - port: {{ .Values.container.port}}    
  selector:
    app: {{ .Values.label.name }}
  type: {{ .Values.service.type }}
