environment: development

apphost: k8s

label:
  name: dotnetapi1

container:
  name: dotnetapi1
  pullPolicy: IfNotPresent
  image: configsamp
  tag: latest
  port: 80
  env: Development  

properties:
  Name : "Neha Oberoi"
  Title : "Himanshu Khanna DevOps"
  MyKey : "appsettings.Dev"

replicas: 1
service:
  type: NodePort
  port: 8888




