environment: development

apphost: k8s

label:
  name: dotnetapi1

container:
  name: dotnetapi1
  pullPolicy: IfNotPresent
  image: containerregistryneha.azurecr.io/dotnetapi
  tag: #{Build.BuildId}#
  port: 80
  env: Production  

properties:
  Name : "Neha Oberoi"
  Title : "Himanshu Khanna DevOps"
  MyKey : "appsettings.Dev"


replicas: 1
service:
  type: LoadBalancer
  port: 80




