environment: development

apphost: k8s

label:
  name: dotnetapi1

container:
  name: dotnetapi1
  pullPolicy: IfNotPresent
  image: mycontainerregistryn.azurecr.io/dotnetapi
  tag: #{Build.BuildId}#
  port: 80
  env: Production  

replicas: 1
service:
  type: LoadBalancer
  port: 80




